services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .env.local
    ports:
      - ${PORT}:3000
    volumes:
    - .:/usr/src/app
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    env_file:
      - .env.local
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - hackcc-network
networks:
  hackcc-network:
    driver: bridge