services:
  account-service:
    image: "ghcr.io/hackcc-official/account-service:latest"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:3000
    networks:
      - hackcc-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/:rw
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq:rw
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:Z
    networks:
      - hackcc-network
networks:
  hackcc-network:
    external: true
